---

- hosts: localhost
  become: yes

  vars_files:
    - vars.yml

  tasks:  
  - name: Include task to secure your machine
    include_tasks: secure.yaml

  - name: Include task to other assigned tasks
    include_tasks: other.yml

  - name: Include task to install redis
    include_tasks: redis.yml
